version: '3.9'

services:
  device-iot-type1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${DEVICE_ID}"
    environment:
      - DEVICE_ID="${DEVICE_TYPE}"

  # device2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: device2
  #   environment:
  #     - DEVICE_ID=device2